"""Added follower auxiliary table to represent followers and followees relationship, and added followers field to User class

Revision ID: 0f8768cb7bee
Revises: 5948acea3601
Create Date: 2017-08-26 13:33:27.008084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8768cb7bee'
down_revision = '5948acea3601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.uid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
