"""change pwdhash

Revision ID: 14e91002e36b
Revises: 7dc70d2bb43d
Create Date: 2017-08-03 23:55:02.456294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e91002e36b'
down_revision = '7dc70d2bb43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pwdhash', sa.String(length=154), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pwdhash')
    # ### end Alembic commands ###
