"""change pwdhash

Revision ID: 532c42ff9f9b
Revises: ebebc2244f05
Create Date: 2017-08-03 23:52:00.184715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532c42ff9f9b'
down_revision = 'ebebc2244f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pwdhash1', sa.String(length=154), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pwdhash1')
    # ### end Alembic commands ###
