"""update

Revision ID: 5948acea3601
Revises: 9e2a0b189e91
Create Date: 2017-08-11 13:52:33.520248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5948acea3601'
down_revision = '9e2a0b189e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_account_name', table_name='users')
    op.create_unique_constraint(None, 'users', ['account_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_account_name', 'users', ['account_name'], unique=True)
    # ### end Alembic commands ###
