"""change pwdhash

Revision ID: 7dc70d2bb43d
Revises: ac0d2483619d
Create Date: 2017-08-03 23:54:44.702642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc70d2bb43d'
down_revision = 'ac0d2483619d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pwdhash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pwdhash', sa.VARCHAR(length=54), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
