"""Added posts filed to user class

Revision ID: 87f8840137a3
Revises: b36724e882a3
Create Date: 2017-08-03 23:10:41.644926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f8840137a3'
down_revision = 'b36724e882a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pwdhash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pwdhash', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
