"""added user accountname to user

Revision ID: 9e2a0b189e91
Revises: 04c715bd4791
Create Date: 2017-08-11 12:56:58.078353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2a0b189e91'
down_revision = '04c715bd4791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_account_name'), 'users', ['account_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_account_name'), table_name='users')
    op.drop_column('users', 'account_name')
    # ### end Alembic commands ###
