"""delete pwdhash1

Revision ID: ac0d2483619d
Revises: 532c42ff9f9b
Create Date: 2017-08-03 23:53:30.116186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0d2483619d'
down_revision = '532c42ff9f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pwdhash1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pwdhash1', sa.VARCHAR(length=154), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
