"""First Migration

Revision ID: f9769bc83708
Revises: 
Create Date: 2017-08-01 01:52:49.526919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9769bc83708'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'pwdhash',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pwdhash',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
